### PR TITLE
Fix some incorrect documents in multiuser doc

### PR DESCRIPTION
**Pull request by kngwyu**
Just removed a comma.

### CODE REVIEW

**Comment by kngwyu** [comment]
I noticed that there's a more serious mistake here (putting password to db), so  I changed the doc accordingly.

**Comment by itutu-tienday** [comment]
@kngwyu 

Thank you very much.
We are planning to release the fixes related to your points in the following pull request.
- #643
- https://github.com/arayabrain/barebone-studio/pull/364/

**Comment by kngwyu** [comment]
Then can I close this one?

**Comment by itutu-tienday** [comment]
@kngwyu 
Yes, the main branch has not been updated yet, but I think it's OK to close it.

**Pull request closed without merging**
